
[global]

# Path to the lpj-guess executable.
guess_path = "/home/drew/code/lpj-guess/dave/build/guess"

# The input module to be used by LPJ-Guess.
input_module = "nc"

# Path to the output directory.
output_directory = "/home/drew/code/lpj-guess/runner/output"

# Number of CPU cores available to the jobs.
cpu_count = 1

# Iff true, the run directories and instruction files will be created but, no
# simulations will be run.
dry_run = true

# Iff true, the processing/setup will be run in parallel. This has no effect
# on job execution. The only real reason to disable this is for debugging.
parallel = false

# Baseline parameter set - currently not using this.
[[parameter_sets]]
name = "baseline"

# Parameter changes for temperate sites.
[[parameter_sets]]
name = "temperate"
TeBE.k_allom2 = [50, 60, 70]
TeBE.k_latosa = [5000, 6000, 7000]

# Parameter changes for tropical sites.
[[parameter_sets]]
name = "tropical"
TrBE.k_allom2 = [30, 40, 50]
TrBE.k_latosa = [5500, 6000, 6500]

# Runs of temperate sites.
[[runs]]
# Name of this run. Used as a prefix for the output directory.
name = "temperate"

# Instruction files to be run.
insfiles = [
    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/CumberlandPlain/CumberlandPlain.ins",
    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Tumbarumba/Tumbarumba.ins",
    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Warra/Warra.ins",
    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/WombatStateForest/WombatStateForest.ins",
]

# The parameter changes to be used for this run.
parameter_sets = ["temperate"]

# If true, all combinations of parameter values are run. If false, one
# simulation is run for each parameter value (per instruction file).
full_factorial = false


# Runs of tropical sites.
[[runs]]
# Name of this run. Used as a prefix for the output directory.
name = "tropical"

# Instruction files to be run.
insfiles = [
    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Litchfield/Litchfield.ins",
    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/RobsonCreek/RobsonCreek.ins",
]

# The parameter changes to be used for this run.
parameter_sets = ["tropical"]

# If true, all combinations of parameter values are run. If false, one
# simulation is run for each parameter value (per instruction file).
full_factorial = false



#insfiles = [
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/AdelaideRiver/AdelaideRiver.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/AliceSpringsMulga/AliceSpringsMulga.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Boyagin/Boyagin.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Calperum/Calperum.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/CapeTribulation/CapeTribulation.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Collie/Collie.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/CowBay/CowBay.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/CumberlandPlain/CumberlandPlain.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/DalyPasture/DalyPasture.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/DalyUncleared/DalyUncleared.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/DryRiver/DryRiver.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Emerald/Emerald.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/FletcherView/FletcherView.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/FoggDam/FoggDam.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Gingin/Gingin.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/GreatWesternWoodlands/GreatWesternWoodlands.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/HowardSprings/HowardSprings.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Litchfield/Litchfield.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Longreach/Longreach.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Otway/Otway.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/RedDirtMelonFarm/RedDirtMelonFarm.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Ridgefield/Ridgefield.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/RiggsCreek/RiggsCreek.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/RobsonCreek/RobsonCreek.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Samford/Samford.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/SilverPlains/SilverPlains.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/SturtPlains/SturtPlains.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/TiTreeEast/TiTreeEast.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Tumbarumba/Tumbarumba.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/WallabyCreek/WallabyCreek.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Warra/Warra.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Whroo/Whroo.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/WombatStateForest/WombatStateForest.ins",
#    "/home/drew/code/lpj-guess/dave/benchmarks/ozflux/Yanco/Yanco.ins",
#]
